const styles = (theme) => ({
  root: {

  },
  heroWrapper: {
    width: '100vw',
    height: '100vh',
  },
  hero: {
    width: '100vw',
    height: '100vh',
    objectFit: 'cover',
    position: 'fixed'
  },
  heroText: {
    position: 'absolute',
    top: '40vh',
    left: 0,
    right: 0,
    bottom: 0,
    textAlign: 'center',
  },
  firstShowcaseWrapper: {
    position: 'relative',
    width: '100vw',
    height: '100vh', // 105vh
  },
  firstShowcaseText: {
    position: 'relative',
    left: '2.5vw',
    top: '2.5vh',
  },
  overlayShadow: {
    zIndex: 200,
    width: '100vw',
    height: '100vh',
    background: 'linear-gradient(0deg, rgba(0,0,0,0.9) 1%, rgba(255,255,255,0) 100%)',
  },
  secondShowcaseWrapper: {
    position: 'relative',
    width: '100vw',
    height: '100vh',
  },
  secondShowcaseText: {
    textAlign: 'right',
    position: 'relative',
    right: '2.5vw',
    top: '2.5vh',
    // background: 'linear-gradient(0.25turn, #00000000, #000000)',
    // boxShadow: '9vw 0px 0px 0px #000000f0',
    // background: 'linear-gradient(0.25turn, #000000f7, #00000054)',
    // boxShadow: '-8vw 0px 0px 0px #000000f0',
    // background: 'linear-gradient(0.25turn, #000000c7, #ffffff00)',
    // boxShadow: '-8vw 0px 0px 0px #000000db',
  },
  infoWrapper: {
    position: 'absolute',
    height: '50vh',
    width: '100vw',
    backgroundColor: theme.palette.background.primary,
    display: 'flex',
    flexWrap: 'nowrap',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column'
  },
  infoText: {
    position: 'relative',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    textAlign: 'center',
    marginTop: '10px'
  },
  profileImg: {
    position: 'relative',
    borderRadius: '50%',
    width: '25vw',
    height: '25vw',
    objectFit: 'cover',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignSelf: 'center',
  },
  profileQuote: {
    display: 'flex',
    flexDirection: 'row',
    // textAlign: 'center',
    alignItems: 'center',
    maxWidth: '80vw',
    marginTop: '15px',
  }
    // root: {
    //   zIndex: 0,
    //   width: '100vw',
    //   height: '100vh',
    //   position: 'relative',
    //   display: 'flex',
    //   alignItems: 'center',
    //   flexDirection: 'column',
    //   backgroundColor: theme.palette.background.primary,
    //   // backgroundImage: 'linear-gradient(to bottom left, #EF9C43 5%, #FC6C0A 50%, #152744 50%, #0A73C8 95%)',
    // },
    // navWrapper: {
    //   position: 'absolute',
    //   zIndex: 999,
    //   width: '100%',
    //   height: '8%',
    //   display: 'flex',
    //   flexDirection: 'column',
    //   justifyContent: 'flex-center',
    //   alignItems: 'center'
    // },
    // line: {
    //   width: '100%',
    //   opacity: 0.2,
    //   zIndex: 999,
    //   position: 'absolute',
    //   top: 79,
    //   left: 0,
    //   margin: 0,
    // },
    // heroWrapper: {
    //   display: 'flex',
    //   flexDirection: 'column',
    //   justifyContent: 'flex-center',
    //   alignItems: 'center',
    //   height: '100vh',
    // },
    // hero: {
    //   alignItems: 'center',
    //   position: 'fixed',
    //   width: '100vw',
    //   height: '100vh',
    //   objectFit: 'cover',
    //   opacity: 0.70,
    // },
    // heroText: {
    //   position: 'absolute',
    //   top: '40vh'
    // },
    // firstShowcaseWrapper: {
    //   // '&:hover': {
    //   //     background: 'linear-gradient(to top, rgba(0,0,0,1) 0%, rgba(0,0,0,0.5) 100%)',
    //   // },
    //   width: '100vw',
    //   height: '115vh',
    //   zIndex: 2,
    //   marginTop: '100vh',
    // },
    // firstShowcase: {
    //   alignItems: 'center',
    //   position: 'absolute',
    //   top: '100vh',
    //   width: '100%',
    //   height: '105%',
    //   objectFit: 'cover',
    //   borderTopLeftRadius: '26px',
    //   borderTopRightRadius: '26px',
    //   // marginBottom: '2.5vw',
    //   background: 'linear-gradient(to top, rgba(0,0,0,1) 0%, rgba(0,0,0,0.5) 100%)',
    // },
    // firstShowcaseText: {
    //   zIndex: 100,
    //   top: '7vh',
    //   position: 'relative',
    //   marginLeft: '3vw',
    //   background: 'linear-gradient(0.25turn, #00000000, #000000)',
    //   boxShadow: '9vw 0px 0px 0px #000000f0',
    // },
    // secondShowcaseWrapper: {
    //   width: '100vw',
    //   height: '100vh',
    //   zIndex: 3,
    //   flex: 1,
    //   marginTop: '100vh',
    //   flexDirection: 'column',
    //   justifyContent: 'center',
    //   alignItems: 'center',
    // },
    // secondShowcase: {
    //   alignItems: 'center',
    //   position: 'absolute',
    //   top: '100vh',
    //   width: '100%',
    //   height: '100%',
    //   objectFit: 'cover',
    //   borderTopLeftRadius: '26px',
    //   borderTopRightRadius: '26px',
    //   marginTop: '100vh',
    //   boxShadow: '0px -20px 20px 20px #00000085',
    // },
    // secondShowcaseText: {
    //   zIndex: 2,
    //   position: 'relative',
    //   textAlign: 'right',
    //   top: '-1.3vh',
    //   marginRight: '5vw',
    //   marginLeft: '50vw',
    //   background: 'linear-gradient(0.25turn, #00000000, #000000)',
    //   boxShadow: '9vw 0px 0px 0px #000000f0',
    //   // background: 'linear-gradient(0.25turn, #000000f7, #00000054)',
    //   // boxShadow: '-8vw 0px 0px 0px #000000f0',
    //   // background: 'linear-gradient(0.25turn, #000000c7, #ffffff00)',
    //   // boxShadow: '-8vw 0px 0px 0px #000000db',
    // },
    // infoWrapper: {
    //   position: 'relative',
    //   height: '100vh',
    //   width: '100vw',
    //   marginTop: '140vh',
    //   display: 'flex',
    //   flexWrap: 'wrap',
    //   flexDirection: 'column',
    //   alignContent: 'center',
    //   justifyContent: 'flex-end',
    // }
});

export default styles;
